### ISSUE TITLE
Please update document for avalonia 11

### ISSUE THREAD

**Issue by butaixianran** [sandreas/Avalonia.SimpleRouter#2]
From avalonia 11, ViewLocator is removed from project template, which is needed by this package but not mentioned in document.

So people need to know, they have to create their own ViewLocator class.

Also, to use this package, we need to install package `Microsoft.Extensions.DependencyInjection`, which is also not mentioned in document.

**Comment by sandreas** [comment]
> So people need to know, they have to create their own ViewLocator class.

Oh, this is interesting. Thanks for clearing this up.

> Also, to use this package, we need to install package Microsoft.Extensions.DependencyInjection, which is also not mentioned in document.

This is a dependency that only provides a small amount of convenience and will be removed in the next release. But thanks for pointing this out :-)

**Comment by sandreas** [comment]
Should now be fixed. Feedback welcome :-) Thansk again for bringing this up.
