### ISSUE TITLE
Next page with parameters?

### ISSUE THREAD

**Issue by michalss** [sandreas/Avalonia.SimpleRouter#3]
Hi Can you please add sample how to pass the selected parameter from first page to other page? I know i can do it statically but it is not the correct way.

**Comment by sandreas** [comment]
Heyho,

there is no need for "Parameters" as specific declared properties. You can just use the `Goto` Method, which returns the ViewModel you're about to transition to:

```C#
// navigate to "Settings"
var settingsVm = router.GoTo<SettingsViewModel>();

// set a value on the destination viewModel
settingsVm.SomeParameter = "ParameterValue";
```

That's it. Is this what you were asking for?
